# JSON examples and exercise
****
+ get familiar with packages for dealing with JSON
+ study examples with JSON strings and files 
+ work on exercise to be completed and submitted 
****
+ reference: http://pandas.pydata.org/pandas-docs/stable/io.html#io-json-reader
+ data source: http://jsonstudio.com/resources/
****

In [ ]:
import pandas as pd

## imports for Python, Pandas

In [ ]:
import json
from pandas.io.json import json_normalize

## JSON example, with string

+ demonstrates creation of normalized dataframes (tables) from nested json string
+ source: http://pandas.pydata.org/pandas-docs/stable/io.html#normalization

In [ ]:
# define json string
data = [{'state': 'Florida', 
         'shortname': 'FL',
         'info': {'governor': 'Rick Scott'},
         'counties': [{'name': 'Dade', 'population': 12345},
                      {'name': 'Broward', 'population': 40000},
                      {'name': 'Palm Beach', 'population': 60000}]},
        {'state': 'Ohio',
         'shortname': 'OH',
         'info': {'governor': 'John Kasich'},
         'counties': [{'name': 'Summit', 'population': 1234},
                      {'name': 'Cuyahoga', 'population': 1337}]}]

In [ ]:
# use normalization to create tables from nested element
json_normalize(data, 'counties')

In [ ]:
# further populate tables created from nested element
json_normalize(data, 'counties', ['state', 'shortname', ['info', 'governor']])

****
## JSON example, with file

+ demonstrates reading in a json file as a string and as a table
+ uses small sample file containing data about projects funded by the World Bank 
+ data source: http://jsonstudio.com/resources/

In [ ]:
# load json as string
json.load((open('data/world_bank_projects_less.json')))

In [ ]:
# load as Pandas dataframe
sample_json_df = pd.read_json('data/world_bank_projects_less.json')
sample_json_df

****
## JSON exercise

Using data in file 'data/world_bank_projects.json' and the techniques demonstrated above,
1. Find the 10 countries with most projects
2. Find the top 10 major project themes (using column 'mjtheme_namecode')
3. In 2. above you will notice that some entries have only the code and the name is missing. Create a dataframe with the missing names filled in.

In [1]:
import pandas as pd

In [2]:
import json
from pandas.io.json import json_normalize

In [3]:
# load as Pandas dataframe
json_df = pd.read_json('data/world_bank_projects.json')
json_df

,_id,approvalfy,board_approval_month,boardapprovaldate,borrower,closingdate,country_namecode,countrycode,countryname,countryshortname,...,sectorcode,source,status,supplementprojectflg,theme1,theme_namecode,themecode,totalamt,totalcommamt,url
0,{'$oid': '52b213b38594d8a2be17c780'},1999,November,2013-11-12T00:00:00Z,FEDERAL DEMOCRATIC REPUBLIC OF ETHIOPIA,2018-07-07T00:00:00Z,Federal Democratic Republic of Ethiopia!$!ET,ET,Federal Democratic Republic of Ethiopia,Ethiopia,...,"ET,BS,ES,EP",IBRD,Active,N,"{'Percent': 100, 'Name': 'Education for all'}","[{'code': '65', 'name': 'Education for all'}]",65,130000000,130000000,http://www.worldbank.org/projects/P129828/ethi...
1,{'$oid': '52b213b38594d8a2be17c781'},2015,November,2013-11-04T00:00:00Z,GOVERNMENT OF TUNISIA,NaN,Republic of Tunisia!$!TN,TN,Republic of Tunisia,Tunisia,...,"BZ,BS",IBRD,Active,N,"{'Percent': 30, 'Name': 'Other economic manage...","[{'code': '24', 'name': 'Other economic manage...","54,24",0,4700000,http://www.worldbank.org/projects/P144674?lang=en
2,{'$oid': '52b213b38594d8a2be17c782'},2014,November,2013-11-01T00:00:00Z,MINISTRY OF FINANCE AND ECONOMIC DEVEL,NaN,Tuvalu!$!TV,TV,Tuvalu,Tuvalu,...,TI,IBRD,Active,Y,"{'Percent': 46, 'Name': 'Regional integration'}","[{'code': '47', 'name': 'Regional integration'...","52,81,25,47",6060000,6060000,http://www.worldbank.org/projects/P145310?lang=en
3,{'$oid': '52b213b38594d8a2be17c783'},2014,October,2013-10-31T00:00:00Z,MIN. OF PLANNING AND INT'L COOPERATION,NaN,Republic of Yemen!$!RY,RY,Republic of Yemen,"Yemen, Republic of",...,JB,IBRD,Active,N,"{'Percent': 50, 'Name': 'Participation and civ...","[{'code': '57', 'name': 'Participation and civ...","59,57",0,1500000,http://www.worldbank.org/projects/P144665?lang=en
4,{'$oid': '52b213b38594d8a2be17c784'},2014,October,2013-10-31T00:00:00Z,MINISTRY OF FINANCE,2019-04-30T00:00:00Z,Kingdom of Lesotho!$!LS,LS,Kingdom of Lesotho,Lesotho,...,"FH,YW,YZ",IBRD,Active,N,"{'Percent': 30, 'Name': 'Export development an...","[{'code': '45', 'name': 'Export development an...","41,45",13100000,13100000,http://www.worldbank.org/projects/P144933/seco...
5,{'$oid': '52b213b38594d8a2be17c785'},2014,October,2013-10-31T00:00:00Z,REPUBLIC OF KENYA,NaN,Republic of Kenya!$!KE,KE,Republic of Kenya,Kenya,...,JB,IBRD,Active,Y,"{'Percent': 100, 'Name': 'Social safety nets'}","[{'code': '54', 'name': 'Social safety nets'}]",54,10000000,10000000,http://www.worldbank.org/projects/P146161?lang=en
6,{'$oid': '52b213b38594d8a2be17c786'},2014,October,2013-10-29T00:00:00Z,GOVERNMENT OF INDIA,2019-06-30T00:00:00Z,Republic of India!$!IN,IN,Republic of India,India,...,TI,IBRD,Active,N,"{'Percent': 20, 'Name': 'Administrative and ci...","[{'code': '25', 'name': 'Administrative and ci...","39,25",500000000,500000000,http://www.worldbank.org/projects/P121185/firs...
7,{'$oid': '52b213b38594d8a2be17c787'},2014,October,2013-10-29T00:00:00Z,PEOPLE'S REPUBLIC OF CHINA,NaN,People's Republic of China!$!CN,CN,People's Republic of China,China,...,LR,IBRD,Active,N,"{'Percent': 100, 'Name': 'Climate change'}","[{'code': '81', 'name': 'Climate change'}]",81,0,27280000,http://www.worldbank.org/projects/P127033/chin...
8,{'$oid': '52b213b38594d8a2be17c788'},2014,October,2013-10-29T00:00:00Z,THE GOVERNMENT OF INDIA,2018-12-31T00:00:00Z,Republic of India!$!IN,IN,Republic of India,India,...,TI,IBRD,Active,N,"{'Percent': 87, 'Name': 'Other rural developme...","[{'code': '79', 'name': 'Other rural developme...",79,160000000,160000000,http://www.worldbank.org/projects/P130164/raja...
9,{'$oid': '52b213b38594d8a2be17c789'},2014,October,2013-10-29T00:00:00Z,THE KINGDOM OF MOROCCO,2014-12-31T00:00:00Z,Kingdom of Morocco!$!MA,MA,Kingdom of Morocco,Morocco,...,"BM,BC,BZ",IBRD,Active,N,"{'Percent': 33, 'Name': 'Other accountability/...","[{'code': '29', 'name': 'Other accountability/...","27,30,29",200000000,200000000,http://www.worldbank.org/projects/P130903?lang=en
10,{'$oid': '52b213b38594d8a2be17c78a'},2014,October,2013-10-25T00:00:00Z,GOVERNMENT OF SOUTH SUDAN,NaN,Republic of South Sudan!$!SS,SS,Republic of South Sudan,South Sudan,...,"AZ,JB,AH",IBRD,Active,Y,"{'Percent': 100, 'Name': 'Global food crisis r...","[{'code': '91', 'name': 'Global food crisis re...",91,0,7530000,http://www.worldbank.org/projects/P145339?lang=en
11,{'$oid': '52b213b38594d8a2be17c78b'},2014,October,2013-10-25T00:00:00Z,NaN,2017-12-31T00:00:00Z,Republic of India!$!IN,IN,Republic of India,India,...,"JB,YC,WD,TI",IBRD,Active,N,"{'Percent': 60, 'Name': 'Rural services and in...","[{'code': '78', 'name': 'Rural services and in...","81,87,52,78",250000000,250000000,http://www.worldbank.org/projects/P146653?lang=en
12,{'$oid': '52b213b38594d8a2be17c78c'},2014,October,2013-10-24T00:00:00Z,GOVERNMENT OF GHANA,2019-06-30T00:00:00Z,Republic of Ghana!$!GH,GH,Republic of Ghana,Ghana,...,CZ,IBRD,Active,N,"{'Percent': 0, 'Name': ''}",NaN,NaN,97000000,97000000,http://www.worldbank.org/projects/P144140/gh-e...
13,{'$oid': '52b213b38594d8a2be17c78d'},2014,October,2013-10-22T00:00:00Z,GOVERNMENT OF TIMOR LESTE,NaN,Democratic Republic of Timor-Leste!$!TP,TP,Democratic Republic of Timor-Leste,Timor-Leste,...,"BV,TI",IBRD,Active,Y,"{'Percent': 20, 'Name': 'Regional integration'}","[{'code': '47', 'name': 'Regional integration'...","78,81,47",40000000,40000000,http://www.worldbank.org/projects/P130975/timo...
14,{'$oid': '52b213b38594d8a2be17c78e'},2014,October,2013-10-22T00:00:00Z,GOVERNMENT OF JORDAN,NaN,Hashemite Kingdom of Jordan!$!JO,JO,Hashemite Kingdom of Jordan,Jordan,...,JB,IBRD,Active,N,"{'Percent': 50, 'Name': 'Social safety nets'}","[{'code': '54', 'name': 'Social safety nets'},...","53,56,54",0,9500000,http://www.worldbank.org/projects/P144832?lang=en
15,{'$oid': '52b213b38594d8a2be17c78f'},2014,October,2013-10-17T00:00:00Z,MINISTRY OF FINANCE,2019-04-30T00:00:00Z,Samoa!$!WS,WS,Samoa,Samoa,...,TI,IBRD,Active,N,"{'Percent': 60, 'Name': 'Rural services and in...","[{'code': '78', 'name': 'Rural services and in...","49,81,78",20000000,20000000,http://www.worldbank.org/projects/P145545?lang=en
16,{'$oid': '52b213b38594d8a2be17c790'},2014,October,2013-10-17T00:00:00Z,MINISTRY OF FINANCE,2015-12-31T00:00:00Z,Samoa!$!WS,WS,Samoa,Samoa,...,"AZ,AJ,AH",IBRD,Active,N,"{'Percent': 100, 'Name': 'Other rural developm...","[{'code': '79', 'name': 'Other rural developme...",79,5000000,5000000,http://www.worldbank.org/projects/P145938?lang=en
17,{'$oid': '52b213b38594d8a2be17c791'},2014,October,2013-10-16T00:00:00Z,MINISTRY OF FINANCE AND BUDGET (MFB),NaN,Republic of Madagascar!$!MG,MG,Republic of Madagascar,Madagascar,...,EP,IBRD,Active,N,"{'Percent': 100, 'Name': 'Education for all'}","[{'code': '65', 'name': 'Education for all'}]",65,0,85400000,http://www.worldbank.org/projects/P132616?lang=en
18,{'$oid': '52b213b38594d8a2be17c792'},2014,October,2013-10-16T00:00:00Z,ROYAL GOVERNMENT OF CAMBODIA,NaN,Kingdom of Cambodia!$!KH,KH,Kingdom of Cambodia,Cambodia,...,"BK,JB,BH,BC,JA",IBRD,Active,Y,"{'Percent': 17, 'Name': 'Child health'}","[{'code': '63', 'name': 'Child health'}, {'cod...","69,57,25,67,63",0,13450000,http://www.worldbank.org/projects/P146271?lang=en
19,{'$oid': '52b213b38594d8a2be17c793'},2014,October,2013-10-10T00:00:00Z,MINISTRY OF FINANCE,NaN,Kingdom of Morocco!$!MA,MA,Kingdom of Morocco,Morocco,...,"BH,BC,BZ",IBRD,Active,N,"{'Percent': 40, 'Name': 'Public expenditure, f...","[{'code': '27', 'name': 'Public expenditure, f...","25,26,27",0,4350000,http://www.worldbank.org/projects/P143979?lang=en
20,{'$oid': '52b213b38594d8a2be17c794'},2014,October,2013-10-09T00:00:00Z,AGA KHAN DEVELOPMENT NETWORK (AKDN),NaN,Kyrgyz Republic!$!KG,KG,Kyrgyz Republic,Kyrgyz Republic,...,JB,IBRD,Active,N,"{'Percent': 50, 'Name': 'Conflict prevention a...","[{'code': '58', 'name': 'Conflict prevention a...","57,58",0,2000000,http://www.worldbank.org/projects/P132577?lang=en
21,{'$oid': '52b213b38594d8a2be17c795'},2014,October,2013-10-07T00:00:00Z,NEPAL,NaN,Nepal!$!NP,NP,Nepal,Nepal,...,"BH,YW,JB",IBRD,Active,N,"{'Percent': 30, 'Name': 'Urban services and ho...","[{'code': '71', 'name': 'Urban services and ho...","57,71",0,2750000,http://www.worldbank.org/projects/P145359?lang=en
22,{'$oid': '52b213b38594d8a2be17c796'},2014,October,2013-10-07T00:00:00Z,MINISTRY OF PLANNING AND INTERNATIONAL C,NaN,Hashemite Kingdom of Jordan!$!JO,JO,Hashemite Kingdom of Jordan,Jordan,...,"WC,BS,BH,TZ,WB",IBRD,Active,N,"{'Percent': 25, 'Name': 'Other social developm...","[{'code': '62', 'name': 'Other social developm...","58,62",0,50000000,http://www.worldbank.org/projects/P147689?lang=en
23,{'$oid': '52b213b38594d8a2be17c797'},2014,October,2013-10-03T00:00:00Z,REPUBLIC OF TAJIKISTAN,NaN,Republic of Tajikistan!$!TJ,TJ,Republic of Tajikistan,Tajikistan,...,JA,IBRD,Active,N,"{'Percent': 60, 'Name': 'Nutrition and food se...","[{'code': '68', 'name': 'Nutrition and food se...","63,68",0,2800000,http://www.worldbank.org/projects/P146109?lang=en
24,{'$oid': '52b213b38594d8a2be17c798'},2014,September,2013-09-30T00:00:00Z,REPUBLIC OF AZERBAIJAN,2018-12-31T00:00:00Z,Republic of Azerbaijan!$!AZ,AZ,Republic of Azerbaijan,Azerbaijan,...,"AB,AZ,YA",IBRD,Active,N,"{'Percent': 30, 'Name': 'Rural markets'}","[{'code': '75', 'name': 'Rural markets'}, {'co...","56,78,76,75",34500000,34500000,http://www.worldbank.org/projects/P122812/thir...
25,{'$oid': '52b213b38594d8a2be17c799'},2014,September,2013-09-30T00:00:00Z,UNIVERSITY OF QUEENSLAND,NaN,East Asia and Pacific!$!4E,4E,East Asia and Pacific,East Asia and Pacific,...,"AB,AZ",IBRD,Active,N,"{'Percent': 40, 'Name': 'Other environment and...","[{'code': '86', 'name': 'Other environment and...","80,81,86",0,4500000,http://www.worldbank.org/projects/P123933/capt...
26,{'$oid': '52b213b38594d8a2be17c79a'},2014,September,2013-09-30T00:00:00Z,LAO PEOPLES DEMOCRATIC REPUBLIC,2014-03-31T00:00:00Z,Lao People's Democratic Republic!$!LA,LA,Lao People's Democratic Republic,Lao People's Democratic Republic,...,"LG,FB,EZ,YZ,BC",IBRD,Closed,N,"{'Percent': 14, 'Name': 'Regulation and compet...","[{'code': '40', 'name': 'Regulation and compet...","67,27,49,40",20000000,20000000,http://www.worldbank.org/projects/P143025/lao-...
27,{'$oid': '52b213b38594d8a2be17c79b'},2014,September,2013-09-30T00:00:00Z,PACIFIC AVIATION SECURITY OFFICE,2018-12-31T00:00:00Z,Pacific Islands!$!4P,4P,Pacific Islands,Pacific Islands,...,"BV,TV",IBRD,Active,N,"{'Percent': 5, 'Name': 'Climate change'}","[{'code': '81', 'name': 'Climate change'}, {'c...","52,47,25,81",2150000,2150000,http://www.worldbank.org/projects/P145057/paci...
28,{'$oid': '52b213b38594d8a2be17c79c'},2014,September,2013-09-30T00:00:00Z,SOLOMON ISLANDS GOVERNMENT,NaN,Solomon Islands!$!SB,SB,Solomon Islands,Solomon Islands,...,"BZ,AZ",IBRD,Active,Y,"{'Percent': 30, 'Name': 'Rural policies and in...","[{'code': '77', 'name': 'Rural policies and in...","57,78,77",3000000,3000000,http://www.worldbank.org/projects/P146021?lang=en
29,{'$oid': '52b213b38594d8a2be17c79d'},2014,September,2013-09-27T00:00:00Z,GOVERNMENT OF MOZAMBIQUE,NaN,Republic of Mozambique!$!MZ,MZ,Republic of Mozambique,Mozambique,...,"JB,BW,WZ,WD",IBRD,Active,Y,"{'Percent': 4, 'Name': 'Other social developme...","[{'code': '62', 'name': 'Other social developm...","85,62",32000000,32000000,http://www.worldbank.org/projects/P146098?lang=en
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
470,{'$oid': '52b213b38594d8a2be17c956'},2013,September,2012-09-20T00:00:00Z,GOVERNMENT OF LIBERIA,NaN,Republic of Liberia!$!LR,LR,Republic of Liberia,Liberia,...,"BV,TI",IBRD,Active,Y,"{'Percent': 40, 'Name': 'Trade facilitation an...","[{'code': '49', 'name': 'Trade facilitation an...","78,49",50000000,50000000,http://www.worldbank.org/projects/P129654/libe...
471,{'$oid': '52b213b38594d8a2be17c957'},2013,September,2012-09-20T00:00:00Z,GOVERNMENT OF BANGLADESH,2018-12-31T00:00:00Z,People's Republic of Bangladesh!$!BD,BD,People's Republic of Bangladesh,Bangladesh,...,"BU,LA,LR",IBRD,Active,N,"{'Percent': 45, 'Name': 'Rural services and in...","[{'code': '78', 'name': 'Rural services and in...","59,81,57,78",155000000,155000000,http://www.worldbank.org/projects/P131263/rura...
472,{'$oid': '52b213b38594d8a2be17c958'},2013,September,2012-09-13T00:00:00Z,MINISTRY OF NATURE PROTECTION,2014-09-30T00:00:00Z,Republic of Armenia!$!AM,AM,Republic of Armenia,Armenia,...,BC,IBRD,Active,N,"{'Percent': 100, 'Name': 'Other environment an...","[{'code': '86', 'name': 'Other environment and...",86,0,150000,http://www.worldbank.org/projects/P131631/repo...
473,{'$oid': '52b213b38594d8a2be17c959'},2013,September,2012-09-13T00:00:00Z,"MINISTRY OF ENVIRONMENT, FORESTS, WATER",NaN,Republic of Albania!$!AL,AL,Republic of Albania,Albania,...,BC,IBRD,Active,N,"{'Percent': 100, 'Name': 'Other environment an...","[{'code': '86', 'name': 'Other environment and...",86,0,150000,http://www.worldbank.org/projects/P132679/land...
474,{'$oid': '52b213b38594d8a2be17c95a'},2013,September,2012-09-11T00:00:00Z,GOVERNMENT OF PAKISTAN,2017-06-30T00:00:00Z,Islamic Republic of Pakistan!$!PK,PK,Islamic Republic of Pakistan,Pakistan,...,"BM,BH",IBRD,Active,N,"{'Percent': 34, 'Name': 'Municipal finance'}","[{'code': '72', 'name': 'Municipal finance'}, ...","73,72",150000000,150000000,http://www.worldbank.org/projects/P112901/pk-p...
475,{'$oid': '52b213b38594d8a2be17c95b'},2013,September,2012-09-11T00:00:00Z,GOVERNMENT OF INDONESIA,2018-03-31T00:00:00Z,Republic of Indonesia!$!ID,ID,Republic of Indonesia,Indonesia,...,"BO,BH,LZ,TZ,WZ",IBRD,Active,N,"{'Percent': 25, 'Name': 'Infrastructure servic...","[{'code': '39', 'name': 'Infrastructure servic...","72,39",29600000,29600000,http://www.worldbank.org/projects/P118916/infr...
476,{'$oid': '52b213b38594d8a2be17c95c'},2013,September,2012-09-11T00:00:00Z,SOCIALIST REPUBLIC OF VIETNAM,2018-12-31T00:00:00Z,Socialist Republic of Vietnam!$!VN,VN,Socialist Republic of Vietnam,Vietnam,...,"BU,LT,LA",IBRD,Active,N,"{'Percent': 100, 'Name': 'Rural services and i...","[{'code': '78', 'name': 'Rural services and in...",78,448900000,448900000,http://www.worldbank.org/projects/P125996/dist...
477,{'$oid': '52b213b38594d8a2be17c95d'},2013,September,2012-09-11T00:00:00Z,REPUBLIC OF UZBEKISTAN,NaN,Republic of Uzbekistan!$!UZ,UZ,Republic of Uzbekistan,Uzbekistan,...,FH,IBRD,Active,Y,"{'Percent': 40, 'Name': 'Micro, Small and Medi...","[{'code': '41', 'name': 'Micro, Small and Medi...","75,41",40000000,40000000,http://www.worldbank.org/projects/P126962/addi...
478,{'$oid': '52b213b38594d8a2be17c95e'},2013,September,2012-09-11T00:00:00Z,ISLAMIC REPUBLIC OF PAKISTAN,NaN,Islamic Republic of Pakistan!$!PK,PK,Islamic Republic of Pakistan,Pakistan,...,BH,IBRD,Active,Y,"{'Percent': 10, 'Name': 'Administrative and ci...","[{'code': '25', 'name': 'Administrative and ci...","83,36,25",70000000,70000000,http://www.worldbank.org/projects/P131266/punj...
479,{'$oid': '52b213b38594d8a2be17c95f'},2013,September,2012-09-10T00:00:00Z,UT'Z CHE,2016-05-07T00:00:00Z,Republic of Guatemala!$!GT,GT,Republic of Guatemala,Guatemala,...,AZ,IBRD,Active,N,"{'Percent': 100, 'Name': 'Other social develop...","[{'code': '62', 'name': 'Other social developm...",62,0,2510000,http://www.worldbank.org/projects/P130412/stre...
480,{'$oid': '52b213b38594d8a2be17c960'},2013,September,2012-09-10T00:00:00Z,GOVERNMENT OF ZAMBIA,2014-12-31T00:00:00Z,Republic of Zambia!$!ZM,ZM,Republic of Zambia,Zambia,...,LS,IBRD,Active,N,"{'Percent': 100, 'Name': 'Other public sector ...","[{'code': '30', 'name': 'Other public sector g...",30,0,350000,http://www.worldbank.org/projects/P131881/zamb...
481,{'$oid': '52b213b38594d8a2be17c961'},2013,September,2012-09-06T00:00:00Z,GOVERNMENT OF INDIA,2015-12-31T00:00:00Z,Republic of India!$!IN,IN,Republic of India,India,...,"BC,EC,BQ,BH",IBRD,Active,N,"{'Percent': 23, 'Name': 'Child health'}","[{'code': '63', 'name': 'Child health'}, {'cod...","68,59,57,63",106000000,106000000,http://www.worldbank.org/projects/P121731/icds...
482,{'$oid': '52b213b38594d8a2be17c962'},2013,September,2012-09-06T00:00:00Z,GOVERNMENT OF INDIA,2018-12-31T00:00:00Z,Republic of India!$!IN,IN,Republic of India,India,...,"AI,YA,AH,BL,AB",IBRD,Active,N,"{'Percent': 10, 'Name': 'Rural services and in...","[{'code': '78', 'name': 'Rural services and in...","79,85,86,78",60000000,60000000,http://www.worldbank.org/projects/P122486/karn...
483,{'$oid': '52b213b38594d8a2be17c963'},2013,September,2012-09-06T00:00:00Z,GOVERNMENT OF INDIA,2013-09-30T00:00:00Z,Republic of India!$!IN,IN,Republic of India,India,...,"CZ,AH,LA,AI,LH",IBRD,Closed,N,"{'Percent': 19, 'Name': 'Pollution management ...","[{'code': '84', 'name': 'Pollution management ...","82,78,81,84",100000000,100000000,http://www.worldbank.org/projects/P124041/hima...
484,{'$oid': '52b213b38594d8a2be17c964'},2013,September,2012-09-06T00:00:00Z,"ILO, MINLAND & CFSI & BANK",2015-12-31T00:00:00Z,Republic of the Philippines!$!PH,PH,Republic of the Philippines,Philippines,...,"EV,FH,BZ,JB",IBRD,Active,Y,"{'Percent': 9, 'Name': 'Rural non-farm income ...","[{'code': '76', 'name': 'Rural non-farm income...","78,58,41,76",0,5570000,http://www.worldbank.org/projects/P132238/mult...
485,{'$oid': '52b213b38594d8a2be17c965'},2013,September,2012-09-05T00:00:00Z,GOVERNMENT OF MONGOLIA,2013-12-31T00:00:00Z,Mongolia!$!MN,MN,Mongolia,Mongolia,...,"BZ,JA,AJ",IBRD,Active,N,"{'Percent': 100, 'Name': 'Other communicable d...","[{'code': '64', 'name': 'Other communicable di...",64,0,2900000,http://www.worldbank.org/projects/P131204/capa...
486,{'$oid': '52b213b38594d8a2be17c966'},2013,September,2012-09-01T00:00:00Z,GOVERNMENT OF LEBANON & JORDAN,2015-01-31T00:00:00Z,Middle East and North Africa!$!5M,5M,Middle East and North Africa,Middle East and North Africa,...,"BZ,BS,BQ,BN",IBRD,Active,N,"{'Percent': 25, 'Name': 'Other public sector g...","[{'code': '30', 'name': 'Other public sector g...","54,55,56,30",0,2400000,http://www.worldbank.org/projects/P132097/5m-d...
487,{'$oid': '52b213b38594d8a2be17c967'},2013,August,2012-08-30T00:00:00Z,UNITED MEXICAN STATES,2017-08-31T00:00:00Z,United Mexican States!$!MX,MX,United Mexican States,Mexico,...,"YA,BL,AB",IBRD,Active,N,"{'Percent': 20, 'Name': 'Biodiversity'}","[{'code': '80', 'name': 'Biodiversity'}, {'cod...","82,79,77,80",0,11690000,http://www.worldbank.org/projects/P121116/sust...
488,{'$oid': '52b213b38594d8a2be17c968'},2013,August,2012-08-30T00:00:00Z,THE STATE OF RIO DE JANEIRO,2014-01-31T00:00:00Z,Federative Republic of Brazil!$!BR,BR,Federative Republic of Brazil,Brazil,...,"JA,EZ,BH",IBRD,Closed,N,"{'Percent': 20, 'Name': 'Health system perform...","[{'code': '67', 'name': 'Health system perform...","65,28,27,67",300000000,300000000,http://www.worldbank.org/projects/P126465/rio-...
489,{'$oid': '52b213b38594d8a2be17c969'},2013,August,2012-08-30T00:00:00Z,UN-HABITAT,2015-06-30T00:00:00Z,The Independent State of Papua New Guine!$!PG,PG,The Independent State of Papua New Guine,Papua New Guinea,...,BW,IBRD,Closed,N,"{'Percent': 50, 'Name': 'Urban services and ho...","[{'code': '71', 'name': 'Urban services and ho...","73,55,52,71",0,350000,http://www.worldbank.org/projects/P128763/papu...
490,{'$oid': '52b213b38594d8a2be17c96a'},2013,August,2012-08-29T00:00:00Z,GOVERNMENT OF NEPAL,2014-06-30T00:00:00Z,Nepal!$!NP,NP,Nepal,Nepal,...,BZ,IBRD,Active,N,"{'Percent': 80, 'Name': 'Public expenditure, f...","[{'code': '27', 'name': 'Public expenditure, f...","29,27",0,800000,http://www.worldbank.org/projects/P131860/stre...
491,{'$oid': '52b213b38594d8a2be17c96b'},2013,August,2012-08-24T00:00:00Z,PALESTINIAN WATER AUTHORITY,2014-03-31T00:00:00Z,West Bank and Gaza!$!GZ,GZ,West Bank and Gaza,West Bank and Gaza,...,"WC,WA",IBRD,Active,N,"{'Percent': 100, 'Name': 'Rural services and i...","[{'code': '78', 'name': 'Rural services and in...",78,0,3650000,http://www.worldbank.org/projects/P123322/wate...

In [4]:
# Find the 10 countries with most projects
df_count = json_df['countryname'].value_counts()
df_count_top_10 = df_count.head(10)
df_count_top_10
print('10 Countries with Most Projects:')
print(df_count_top_10.head(10))

10 Countries with Most Projects:
People's Republic of China         19
Republic of Indonesia              19
Socialist Republic of Vietnam      17
Republic of India                  16
Republic of Yemen                  13
People's Republic of Bangladesh    12
Nepal                              12
Kingdom of Morocco                 12
Africa                             11
Republic of Mozambique             11
Name: countryname, dtype: int64

In [5]:
# Find the top 10 major project themes (using column 'mjtheme_namecode')
# Look at the content in mjtheme_namecode
df_count = json_df['mjtheme_namecode']
df_count

0      [{'code': '8', 'name': 'Human development'}, {...
1      [{'code': '1', 'name': 'Economic management'},...
2      [{'code': '5', 'name': 'Trade and integration'...
3      [{'code': '7', 'name': 'Social dev/gender/incl...
4      [{'code': '5', 'name': 'Trade and integration'...
5      [{'code': '6', 'name': 'Social protection and ...
6      [{'code': '2', 'name': 'Public sector governan...
7      [{'code': '11', 'name': 'Environment and natur...
8      [{'code': '10', 'name': 'Rural development'}, ...
9      [{'code': '2', 'name': 'Public sector governan...
10     [{'code': '10', 'name': 'Rural development'}, ...
11     [{'code': '10', 'name': 'Rural development'}, ...
12                           [{'code': '4', 'name': ''}]
13     [{'code': '5', 'name': 'Trade and integration'...
14     [{'code': '6', 'name': 'Social protection and ...
15     [{'code': '10', 'name': 'Rural development'}, ...
16     [{'code': '10', 'name': 'Rural development'}, ...
17     [{'code': '8', 'name': 'Human development'}, {...
18     [{'code': '8', 'name': 'Human development'}, {...
19     [{'code': '2', 'name': 'Public sector governan...
20     [{'code': '7', 'name': 'Social dev/gender/incl...
21     [{'code': '9', 'name': 'Urban development'}, {...
22     [{'code': '7', 'name': 'Social dev/gender/incl...
23     [{'code': '8', 'name': 'Human development'}, {...
24     [{'code': '10', 'name': 'Rural development'}, ...
25     [{'code': '11', 'name': 'Environment and natur...
26     [{'code': '4', 'name': 'Financial and private ...
27     [{'code': '11', 'name': 'Environment and natur...
28     [{'code': '10', 'name': 'Rural development'}, ...
29     [{'code': '7', 'name': 'Social dev/gender/incl...
                             ...
470    [{'code': '5', 'name': 'Trade and integration'...
471    [{'code': '10', 'name': 'Rural development'}, ...
472    [{'code': '11', 'name': 'Environment and natur...
473    [{'code': '11', 'name': 'Environment and natur...
474    [{'code': '9', 'name': 'Urban development'}, {...
475    [{'code': '4', 'name': 'Financial and private ...
476    [{'code': '10', 'name': 'Rural development'}, ...
477    [{'code': '4', 'name': 'Financial and private ...
478    [{'code': '2', 'name': 'Public sector governan...
479    [{'code': '7', 'name': 'Social dev/gender/incl...
480    [{'code': '2', 'name': 'Public sector governan...
481    [{'code': '8', 'name': 'Human development'}, {...
482    [{'code': '10', 'name': 'Rural development'}, ...
483    [{'code': '11', 'name': 'Environment and natur...
484    [{'code': '10', 'name': 'Rural development'}, ...
485    [{'code': '8', 'name': 'Human development'}, {...
486    [{'code': '2', 'name': 'Public sector governan...
487    [{'code': '11', 'name': 'Environment and natur...
488    [{'code': '8', 'name': 'Human development'}, {...
489    [{'code': '9', 'name': 'Urban development'}, {...
490    [{'code': '2', 'name': 'Public sector governan...
491    [{'code': '10', 'name': 'Rural development'}, ...
492    [{'code': '8', 'name': 'Human development'}, {...
493    [{'code': '11', 'name': 'Environment and natur...
494    [{'code': '6', 'name': 'Social protection and ...
495    [{'code': '4', 'name': 'Financial and private ...
496    [{'code': '8', 'name': 'Human development'}, {...
497    [{'code': '10', 'name': 'Rural development'}, ...
498    [{'code': '10', 'name': 'Rural development'}, ...
499    [{'code': '9', 'name': 'Urban development'}, {...
Name: mjtheme_namecode, Length: 500, dtype: object

In [6]:
# Convert the object to one json file
converted_json = json.loads(json_df.mjtheme_namecode.to_json(orient='values'))

# Break down the json list using chain from the itertools library
from itertools import chain
break_down_list = list(chain.from_iterable(converted_json))
break_down_list[:10]

[{'code': '8', 'name': 'Human development'},
 {'code': '11', 'name': ''},
 {'code': '1', 'name': 'Economic management'},
 {'code': '6', 'name': 'Social protection and risk management'},
 {'code': '5', 'name': 'Trade and integration'},
 {'code': '2', 'name': 'Public sector governance'},
 {'code': '11', 'name': 'Environment and natural resources management'},
 {'code': '6', 'name': 'Social protection and risk management'},
 {'code': '7', 'name': 'Social dev/gender/inclusion'},
 {'code': '7', 'name': 'Social dev/gender/inclusion'}]

In [7]:
break_down_df = pd.DataFrame(break_down_list)
project_count = break_down_df['name'].value_counts()
print('10 Major Project themes:')
print(project_count.head(10))

10 Major Project themes:
Environment and natural resources management    223
Rural development                               202
Human development                               197
Public sector governance                        184
Social protection and risk management           158
Financial and private sector development        130
                                                122
Social dev/gender/inclusion                     119
Trade and integration                            72
Urban development                                47
Name: name, dtype: int64

In [8]:
# Above you will notice that some entries have only the code and the name is missing. 
# Create a dataframe with the missing names filled in.

# Iterate over DataFrame rows as namedtuples.
for row in break_down_df.itertuples():
    print(row)

Pandas(Index=0, code='8', name='Human development')
Pandas(Index=1, code='11', name='')
Pandas(Index=2, code='1', name='Economic management')
Pandas(Index=3, code='6', name='Social protection and risk management')
Pandas(Index=4, code='5', name='Trade and integration')
Pandas(Index=5, code='2', name='Public sector governance')
Pandas(Index=6, code='11', name='Environment and natural resources management')
Pandas(Index=7, code='6', name='Social protection and risk management')
Pandas(Index=8, code='7', name='Social dev/gender/inclusion')
Pandas(Index=9, code='7', name='Social dev/gender/inclusion')
Pandas(Index=10, code='5', name='Trade and integration')
Pandas(Index=11, code='4', name='Financial and private sector development')
Pandas(Index=12, code='6', name='Social protection and risk management')
Pandas(Index=13, code='6', name='')
Pandas(Index=14, code='2', name='Public sector governance')
Pandas(Index=15, code='4', name='Financial and private sector development')
Pandas(Index=16, code='11', name='Environment and natural resources management')
Pandas(Index=17, code='8', name='')
Pandas(Index=18, code='10', name='Rural development')
Pandas(Index=19, code='7', name='')
Pandas(Index=20, code='2', name='Public sector governance')
Pandas(Index=21, code='2', name='Public sector governance')
Pandas(Index=22, code='2', name='Public sector governance')
Pandas(Index=23, code='10', name='Rural development')
Pandas(Index=24, code='2', name='')
Pandas(Index=25, code='10', name='Rural development')
Pandas(Index=26, code='6', name='Social protection and risk management')
Pandas(Index=27, code='6', name='Social protection and risk management')
Pandas(Index=28, code='11', name='Environment and natural resources management')
Pandas(Index=29, code='4', name='')
Pandas(Index=30, code='5', name='Trade and integration')
Pandas(Index=31, code='11', name='Environment and natural resources management')
Pandas(Index=32, code='10', name='Rural development')
Pandas(Index=33, code='6', name='Social protection and risk management')
Pandas(Index=34, code='6', name='Social protection and risk management')
Pandas(Index=35, code='6', name='Social protection and risk management')
Pandas(Index=36, code='10', name='Rural development')
Pandas(Index=37, code='11', name='Environment and natural resources management')
Pandas(Index=38, code='5', name='Trade and integration')
Pandas(Index=39, code='10', name='Rural development')
Pandas(Index=40, code='2', name='')
Pandas(Index=41, code='8', name='Human development')
Pandas(Index=42, code='7', name='')
Pandas(Index=43, code='8', name='Human development')
Pandas(Index=44, code='8', name='Human development')
Pandas(Index=45, code='2', name='Public sector governance')
Pandas(Index=46, code='7', name='Social dev/gender/inclusion')
Pandas(Index=47, code='8', name='Human development')
Pandas(Index=48, code='2', name='Public sector governance')
Pandas(Index=49, code='2', name='Public sector governance')
Pandas(Index=50, code='2', name='Public sector governance')
Pandas(Index=51, code='7', name='Social dev/gender/inclusion')
Pandas(Index=52, code='7', name='Social dev/gender/inclusion')
Pandas(Index=53, code='9', name='Urban development')
Pandas(Index=54, code='7', name='Social dev/gender/inclusion')
Pandas(Index=55, code='7', name='Social dev/gender/inclusion')
Pandas(Index=56, code='7', name='Social dev/gender/inclusion')
Pandas(Index=57, code='8', name='Human development')
Pandas(Index=58, code='8', name='Human development')
Pandas(Index=59, code='10', name='Rural development')
Pandas(Index=60, code='10', name='Rural development')
Pandas(Index=61, code='10', name='Rural development')
Pandas(Index=62, code='6', name='Social protection and risk management')
Pandas(Index=63, code='11', name='Environment and natural resources management')
Pandas(Index=64, code='11', name='Environment and natural resources management')
Pandas(Index=65, code='11', name='Environment and natural resources management')
Pandas(Index=66, code='4', name='Financial and private sector development')
Pandas(Index=67, code='5', name='Trade and integration')
Pandas(Index=68, code='2', name='Public sector governance')
Pandas(Index=69, code='8', name='Human development')
Pandas(Index=70, code='11', name='Environment and natural resources management')
Pandas(Index=71, code='2', name='Public sector governance')
Pandas(Index=72, code='5', name='Trade and integration')
Pandas(Index=73, code='6', name='Social protection and risk management')
Pandas(Index=74, code='10', name='Rural development')
Pandas(Index=75, code='10', name='Rural development')
Pandas(Index=76, code='7', name='Social dev/gender/inclusion')
Pandas(Index=77, code='7', name='Social dev/gender/inclusion')
Pandas(Index=78, code='11', name='Environment and natural resources management')
Pandas(Index=79, code='8', name='Human development')
Pandas(Index=80, code='4', name='')
Pandas(Index=81, code='11', name='Environment and natural resources management')
Pandas(Index=82, code='11', name='Environment and natural resources management')
Pandas(Index=83, code='11', name='Environment and natural resources management')
Pandas(Index=84, code='11', name='Environment and natural resources management')
Pandas(Index=85, code='11', name='Environment and natural resources management')
Pandas(Index=86, code='4', name='Financial and private sector development')
Pandas(Index=87, code='6', name='Social protection and risk management')
Pandas(Index=88, code='1', name='Economic management')
Pandas(Index=89, code='4', name='Financial and private sector development')
Pandas(Index=90, code='2', name='Public sector governance')
Pandas(Index=91, code='8', name='Human development')
Pandas(Index=92, code='5', name='Trade and integration')
Pandas(Index=93, code='5', name='Trade and integration')
Pandas(Index=94, code='7', name='Social dev/gender/inclusion')
Pandas(Index=95, code='10', name='Rural development')
Pandas(Index=96, code='4', name='Financial and private sector development')
Pandas(Index=97, code='10', name='Rural development')
Pandas(Index=98, code='11', name='')
Pandas(Index=99, code='6', name='Social protection and risk management')
Pandas(Index=100, code='7', name='')
Pandas(Index=101, code='11', name='Environment and natural resources management')
Pandas(Index=102, code='11', name='Environment and natural resources management')
Pandas(Index=103, code='6', name='Social protection and risk management')
Pandas(Index=104, code='11', name='Environment and natural resources management')
Pandas(Index=105, code='11', name='Environment and natural resources management')
Pandas(Index=106, code='2', name='Public sector governance')
Pandas(Index=107, code='4', name='')
Pandas(Index=108, code='11', name='Environment and natural resources management')
Pandas(Index=109, code='6', name='Social protection and risk management')
Pandas(Index=110, code='11', name='Environment and natural resources management')
Pandas(Index=111, code='11', name='Environment and natural resources management')
Pandas(Index=112, code='4', name='Financial and private sector development')
Pandas(Index=113, code='8', name='Human development')
Pandas(Index=114, code='2', name='Public sector governance')
Pandas(Index=115, code='2', name='Public sector governance')
Pandas(Index=116, code='2', name='Public sector governance')
Pandas(Index=117, code='8', name='')
Pandas(Index=118, code='11', name='Environment and natural resources management')
Pandas(Index=119, code='7', name='')
Pandas(Index=120, code='8', name='Human development')
Pandas(Index=121, code='10', name='')
Pandas(Index=122, code='2', name='Public sector governance')
Pandas(Index=123, code='10', name='Rural development')
Pandas(Index=124, code='4', name='Financial and private sector development')
Pandas(Index=125, code='4', name='Financial and private sector development')
Pandas(Index=126, code='11', name='Environment and natural resources management')
Pandas(Index=127, code='11', name='')
Pandas(Index=128, code='4', name='Financial and private sector development')
Pandas(Index=129, code='4', name='Financial and private sector development')
Pandas(Index=130, code='7', name='Social dev/gender/inclusion')
Pandas(Index=131, code='6', name='Social protection and risk management')
Pandas(Index=132, code='2', name='Public sector governance')
Pandas(Index=133, code='11', name='Environment and natural resources management')
Pandas(Index=134, code='4', name='')
Pandas(Index=135, code='11', name='Environment and natural resources management')
Pandas(Index=136, code='11', name='Environment and natural resources management')
Pandas(Index=137, code='11', name='Environment and natural resources management')
Pandas(Index=138, code='11', name='Environment and natural resources management')
Pandas(Index=139, code='11', name='Environment and natural resources management')
Pandas(Index=140, code='11', name='Environment and natural resources management')
Pandas(Index=141, code='11', name='Environment and natural resources management')
Pandas(Index=142, code='10', name='Rural development')
Pandas(Index=143, code='2', name='Public sector governance')
Pandas(Index=144, code='5', name='Trade and integration')
Pandas(Index=145, code='2', name='Public sector governance')
Pandas(Index=146, code='8', name='Human development')
Pandas(Index=147, code='8', name='Human development')
Pandas(Index=148, code='8', name='Human development')
Pandas(Index=149, code='11', name='Environment and natural resources management')
Pandas(Index=150, code='7', name='Social dev/gender/inclusion')
Pandas(Index=151, code='11', name='Environment and natural resources management')
Pandas(Index=152, code='11', name='Environment and natural resources management')
Pandas(Index=153, code='11', name='Environment and natural resources management')
Pandas(Index=154, code='4', name='Financial and private sector development')
Pandas(Index=155, code='4', name='Financial and private sector development')
Pandas(Index=156, code='11', name='Environment and natural resources management')
Pandas(Index=157, code='2', name='Public sector governance')
Pandas(Index=158, code='10', name='Rural development')
Pandas(Index=159, code='10', name='Rural development')
Pandas(Index=160, code='11', name='Environment and natural resources management')
Pandas(Index=161, code='11', name='Environment and natural resources management')
Pandas(Index=162, code='2', name='Public sector governance')
Pandas(Index=163, code='7', name='Social dev/gender/inclusion')
Pandas(Index=164, code='2', name='Public sector governance')
Pandas(Index=165, code='10', name='')
Pandas(Index=166, code='5', name='Trade and integration')
Pandas(Index=167, code='6', name='Social protection and risk management')
Pandas(Index=168, code='10', name='Rural development')
Pandas(Index=169, code='10', name='Rural development')
Pandas(Index=170, code='11', name='Environment and natural resources management')
Pandas(Index=171, code='4', name='')
Pandas(Index=172, code='6', name='Social protection and risk management')
Pandas(Index=173, code='2', name='')
Pandas(Index=174, code='6', name='Social protection and risk management')
Pandas(Index=175, code='1', name='Economic management')
Pandas(Index=176, code='2', name='Public sector governance')
Pandas(Index=177, code='11', name='Environment and natural resources management')
Pandas(Index=178, code='2', name='Public sector governance')
Pandas(Index=179, code='4', name='Financial and private sector development')
Pandas(Index=180, code='7', name='Social dev/gender/inclusion')
Pandas(Index=181, code='10', name='Rural development')
Pandas(Index=182, code='5', name='Trade and integration')
Pandas(Index=183, code='9', name='Urban development')
Pandas(Index=184, code='11', name='Environment and natural resources management')
Pandas(Index=185, code='7', name='')
Pandas(Index=186, code='8', name='Human development')
Pandas(Index=187, code='11', name='')
Pandas(Index=188, code='7', name='Social dev/gender/inclusion')
Pandas(Index=189, code='6', name='Social protection and risk management')
Pandas(Index=190, code='8', name='Human development')
Pandas(Index=191, code='8', name='Human development')
Pandas(Index=192, code='8', name='Human development')
Pandas(Index=193, code='4', name='Financial and private sector development')
Pandas(Index=194, code='9', name='Urban development')
Pandas(Index=195, code='10', name='Rural development')
Pandas(Index=196, code='11', name='Environment and natural resources management')
Pandas(Index=197, code='4', name='')
Pandas(Index=198, code='4', name='Financial and private sector development')
Pandas(Index=199, code='4', name='Financial and private sector development')
Pandas(Index=200, code='9', name='Urban development')
Pandas(Index=201, code='5', name='')
Pandas(Index=202, code='2', name='Public sector governance')
Pandas(Index=203, code='5', name='Trade and integration')
Pandas(Index=204, code='1', name='Economic management')
Pandas(Index=205, code='1', name='Economic management')
Pandas(Index=206, code='8', name='Human development')
Pandas(Index=207, code='4', name='Financial and private sector development')
Pandas(Index=208, code='4', name='Financial and private sector development')
Pandas(Index=209, code='11', name='Environment and natural resources management')
Pandas(Index=210, code='11', name='')
Pandas(Index=211, code='2', name='Public sector governance')
Pandas(Index=212, code='1', name='')
Pandas(Index=213, code='6', name='Social protection and risk management')
Pandas(Index=214, code='6', name='Social protection and risk management')
Pandas(Index=215, code='6', name='Social protection and risk management')
Pandas(Index=216, code='2', name='Public sector governance')
Pandas(Index=217, code='10', name='')
Pandas(Index=218, code='2', name='Public sector governance')
Pandas(Index=219, code='4', name='Financial and private sector development')
Pandas(Index=220, code='1', name='Economic management')
Pandas(Index=221, code='6', name='Social protection and risk management')
Pandas(Index=222, code='1', name='Economic management')
Pandas(Index=223, code='1', name='Economic management')
Pandas(Index=224, code='7', name='Social dev/gender/inclusion')
Pandas(Index=225, code='5', name='Trade and integration')
Pandas(Index=226, code='2', name='Public sector governance')
Pandas(Index=227, code='2', name='Public sector governance')
Pandas(Index=228, code='8', name='Human development')
Pandas(Index=229, code='8', name='Human development')
Pandas(Index=230, code='4', name='')
Pandas(Index=231, code='2', name='Public sector governance')
Pandas(Index=232, code='6', name='')
Pandas(Index=233, code='11', name='')
Pandas(Index=234, code='2', name='Public sector governance')
Pandas(Index=235, code='4', name='')
Pandas(Index=236, code='7', name='Social dev/gender/inclusion')
Pandas(Index=237, code='8', name='Human development')
Pandas(Index=238, code='8', name='Human development')
Pandas(Index=239, code='8', name='Human development')
Pandas(Index=240, code='8', name='')
Pandas(Index=241, code='4', name='Financial and private sector development')
Pandas(Index=242, code='11', name='')
Pandas(Index=243, code='11', name='Environment and natural resources management')
Pandas(Index=244, code='4', name='Financial and private sector development')
Pandas(Index=245, code='8', name='Human development')
Pandas(Index=246, code='5', name='Trade and integration')
Pandas(Index=247, code='4', name='Financial and private sector development')
Pandas(Index=248, code='7', name='Social dev/gender/inclusion')
Pandas(Index=249, code='1', name='Economic management')
Pandas(Index=250, code='6', name='Social protection and risk management')
Pandas(Index=251, code='4', name='Financial and private sector development')
Pandas(Index=252, code='3', name='Rule of law')
Pandas(Index=253, code='4', name='Financial and private sector development')
Pandas(Index=254, code='4', name='Financial and private sector development')
Pandas(Index=255, code='10', name='Rural development')
Pandas(Index=256, code='10', name='Rural development')
Pandas(Index=257, code='10', name='Rural development')
Pandas(Index=258, code='10', name='Rural development')
Pandas(Index=259, code='10', name='Rural development')
Pandas(Index=260, code='7', name='Social dev/gender/inclusion')
Pandas(Index=261, code='10', name='Rural development')
Pandas(Index=262, code='10', name='Rural development')
Pandas(Index=263, code='5', name='Trade and integration')
Pandas(Index=264, code='4', name='Financial and private sector development')
Pandas(Index=265, code='5', name='Trade and integration')
Pandas(Index=266, code='5', name='Trade and integration')
Pandas(Index=267, code='5', name='Trade and integration')
Pandas(Index=268, code='2', name='Public sector governance')
Pandas(Index=269, code='10', name='Rural development')
Pandas(Index=270, code='11', name='Environment and natural resources management')
Pandas(Index=271, code='10', name='Rural development')
Pandas(Index=272, code='10', name='Rural development')
Pandas(Index=273, code='10', name='Rural development')
Pandas(Index=274, code='4', name='Financial and private sector development')
Pandas(Index=275, code='10', name='')
Pandas(Index=276, code='2', name='')
Pandas(Index=277, code='11', name='')
Pandas(Index=278, code='8', name='Human development')
Pandas(Index=279, code='8', name='Human development')
Pandas(Index=280, code='2', name='Public sector governance')
Pandas(Index=281, code='5', name='Trade and integration')
Pandas(Index=282, code='6', name='Social protection and risk management')
Pandas(Index=283, code='11', name='Environment and natural resources management')
Pandas(Index=284, code='11', name='Environment and natural resources management')
Pandas(Index=285, code='4', name='Financial and private sector development')
Pandas(Index=286, code='5', name='Trade and integration')
Pandas(Index=287, code='11', name='Environment and natural resources management')
Pandas(Index=288, code='2', name='Public sector governance')
Pandas(Index=289, code='2', name='Public sector governance')
Pandas(Index=290, code='2', name='Public sector governance')
Pandas(Index=291, code='11', name='Environment and natural resources management')
Pandas(Index=292, code='6', name='Social protection and risk management')
Pandas(Index=293, code='7', name='Social dev/gender/inclusion')
Pandas(Index=294, code='11', name='Environment and natural resources management')
Pandas(Index=295, code='7', name='Social dev/gender/inclusion')
Pandas(Index=296, code='4', name='Financial and private sector development')
Pandas(Index=297, code='2', name='')
Pandas(Index=298, code='7', name='Social dev/gender/inclusion')
Pandas(Index=299, code='6', name='Social protection and risk management')
Pandas(Index=300, code='6', name='Social protection and risk management')
Pandas(Index=301, code='2', name='Public sector governance')
Pandas(Index=302, code='8', name='Human development')
Pandas(Index=303, code='10', name='Rural development')
Pandas(Index=304, code='7', name='Social dev/gender/inclusion')
Pandas(Index=305, code='8', name='Human development')
Pandas(Index=306, code='2', name='Public sector governance')
Pandas(Index=307, code='8', name='Human development')
Pandas(Index=308, code='6', name='Social protection and risk management')
Pandas(Index=309, code='7', name='Social dev/gender/inclusion')
Pandas(Index=310, code='2', name='Public sector governance')
Pandas(Index=311, code='6', name='Social protection and risk management')
Pandas(Index=312, code='2', name='Public sector governance')
Pandas(Index=313, code='4', name='Financial and private sector development')
Pandas(Index=314, code='10', name='Rural development')
Pandas(Index=315, code='8', name='Human development')
Pandas(Index=316, code='4', name='Financial and private sector development')
Pandas(Index=317, code='5', name='Trade and integration')
Pandas(Index=318, code='9', name='Urban development')
Pandas(Index=319, code='2', name='Public sector governance')

In [9]:
# Create a blank dictionary and map all the non-blank entries into the dictionary
code_dict = {}
for row in break_down_df.itertuples():
        if row[2] != '':
            code_dict[row[1]] = row[2]
code_dict

{'8': 'Human development',
 '1': 'Economic management',
 '6': 'Social protection and risk management',
 '5': 'Trade and integration',
 '2': 'Public sector governance',
 '11': 'Environment and natural resources management',
 '7': 'Social dev/gender/inclusion',
 '4': 'Financial and private sector development',
 '10': 'Rural development',
 '9': 'Urban development',
 '3': 'Rule of law'}

In [10]:
# Fill in missing theme names with code dictionary
for row in break_down_df.itertuples():
    if row[2] == '':
        break_down_df.set_value(row[0], 'name', code_dict[row[1]])

c:\users\alanl\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:4: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  after removing the cwd from sys.path.

In [11]:
break_down_df

     code                                          name
0       8                             Human development
1      11  Environment and natural resources management
2       1                           Economic management
3       6         Social protection and risk management
4       5                         Trade and integration
5       2                      Public sector governance
6      11  Environment and natural resources management
7       6         Social protection and risk management
8       7                   Social dev/gender/inclusion
9       7                   Social dev/gender/inclusion
10      5                         Trade and integration
11      4      Financial and private sector development
12      6         Social protection and risk management
13      6         Social protection and risk management
14      2                      Public sector governance
15      4      Financial and private sector development
16     11  Environment and natural resources management
17      8                             Human development
18     10                             Rural development
19      7                   Social dev/gender/inclusion
20      2                      Public sector governance
21      2                      Public sector governance
22      2                      Public sector governance
23     10                             Rural development
24      2                      Public sector governance
25     10                             Rural development
26      6         Social protection and risk management
27      6         Social protection and risk management
28     11  Environment and natural resources management
29      4      Financial and private sector development
...   ...                                           ...
1469    8                             Human development
1470    9                             Urban development
1471    6         Social protection and risk management
1472    6         Social protection and risk management
1473    9                             Urban development
1474    2                      Public sector governance
1475    2                      Public sector governance
1476   10                             Rural development
1477   11  Environment and natural resources management
1478    8                             Human development
1479    7                   Social dev/gender/inclusion
1480   11  Environment and natural resources management
1481    5                         Trade and integration
1482    6         Social protection and risk management
1483    8                             Human development
1484    4      Financial and private sector development
1485    7                   Social dev/gender/inclusion
1486    8                             Human development
1487    5                         Trade and integration
1488    2                      Public sector governance
1489    8                             Human development
1490   10                             Rural development
1491    6         Social protection and risk management
1492   10                             Rural development
1493   10                             Rural development
1494   10                             Rural development
1495    9                             Urban development
1496    8                             Human development
1497    5                         Trade and integration
1498    4      Financial and private sector development

[1499 rows x 2 columns]

In [23]:
# Check if there are still any missing values
var = break_down_df.isnull().values.any()
var = True
print('There are no missing values')
if not var:
        print('There are some missing values')

There are no missing values